// Re-export Sequelize models for backward compatibility with controller imports.
// Controllers should be updated to use Sequelize API (findOne({ where }), findByPk, etc.)
export {
  User,
  Post,
  Comment,
  Hashtag,
  Report,
  Share,
  Conversation,
  Message,
  UserFollow,
  PostLike,
  PostHashtag,
  PostMention,
  CommentLike,
  UserMedia,
  UserLikedPost,
  UserCommentedPost,
  ConversationParticipant,
  ConversationBlockedBy,
  ConversationDeletedBy,
  MessageReadBy,
  MessageReaction,
  MessageStarredBy,
  MessageDeletedBy,
  PostReport,
  MessageReport,
  CustomList,
  sequelize,
} from '../database/index.js';
